### PR TITLE
Added missing translation to Portuguese and removed XBMC references

### PR DESCRIPTION
**Pull request by gvasco**
Added missing translations to Portuguese/strings.po and removed XBMC
references in English/strings.po

### CODE REVIEW

**Comment by Tgxcorporation** [comment]
I think "PleKodi" is a typo and should be "PlexKodi" instead. I googled for "PlexKodi" and the results were still regarding PleXbmc. The official repository is still called PleXbmc. I think we should stick with the original name.

**Comment by gvasco** [comment]
That's fine, it's was just cause I noticed in some places it had been changed around so when I spotted those I thought I'd change them as well.

**Comment by Tgxcorporation** [comment]
Should i merge your pull request and then edit it by myself or are you going to make a new pull request?

**Comment by gvasco** [comment]
I can try make a new pull request with just the Portuguese translations.

**Comment by Tgxcorporation** [comment]
Ok. That's better. Thanks.

**Comment by gvasco** [comment]
Is it Ok like this? Still new and trying to figure out how it all works.

**Comment by Tgxcorporation** [comment]
It seems ok. Now i try to merge it in my master branch.

**Pull request merged**
